services:
  - type: web
    name: bombones-noc-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
